/**
* Generated by master4j at ${date}
*
* Copyright (c) 2015-2025 Yannis Zhao, All rights reserved.
*
* http://www.yanniszhao.org     zhaoyjun0222@gmail.com
*
*/
package ${package};

import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = {"classpath*:spring-*.xml"})
public class BaseTest {
}
